# CONFIGURAÇÃO GERAL DA APLICAÇÃO

spring.application.name=LojaCarros

# Alterna dinamicamente entre perfis (dev, prod).
# Se a variável de ambiente SERVER não for informada no sistema, o Spring assume 'dev' como padrão.
spring.profiles.active=${SERVER:dev}


# CONFIGURAÇÕES DE TAXA DE REQUISIÇÕES (RATE LIMITING - BUCKET4J)

# Define o limite máximo de requisições (1000) por janela de tempo (1 minuto)
app.rate-limit.capacity=1000
app.rate-limit.duration-minutes=1


# CONEXÃO COM O BANCO DE DADOS (COM FALLBACK PARA DESENVOLVIMENTO)
# Nota: Em ambiente multifonte, as propriedades abaixo usam sintaxe ${VARIAVEL:valor_padrao}.
# Se a variável de ambiente não existir na máquina/servidor, o valor após os dois-pontos é utilizado.


# URL para dev e prod apontando para a base 'carros'
#spring.datasource.url=jdbc:mysql://localhost:3306/carros?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# Credenciais de acesso ao banco (Valores padrão: usuário 'LDENNER' e senha '12345')
# spring.datasource.username=${DB_USER:LDENNER}
# spring.datasource.password=${DB_PASS:12345}

# Alterado de 'lojacarro' para 'carros' para conectar ao banco configurado no phpMyAdmin
# spring.datasource.url=jdbc:mysql://localhost:3306/lojacarro?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/carros?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ===================================================================
# Dialeto específico para geração do SQL compatível com MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Estratégia do schema: 'update' (atualiza/cria tabelas automaticamente em Dev)
# ou 'validate' (apenas valida se o banco está correto em Prod)
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# Exibe no terminal as queries SQL executadas pelo Hibernate e as formata para facilitar a leitura
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===================================================================
# CONFIGURAÇÕES DE LOGS E AUDITORIA (JAVERS + LOGBACK + MDC)
# ===================================================================
# Padrão de saída no console com Data, Hora, Nível, Usuário do JWT e IP
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [User: %X{usuario:-SISTEMA}] [IP: %X{ip:-LOCAL}] - %msg%n

# Arquivo onde todos os logs de auditoria serão gravados
logging.file.name=logs/lojacarro-audit.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [User: %X{usuario:-SISTEMA}] [IP: %X{ip:-LOCAL}] %msg%n